accounts/urls.py
from django.urls import path

from accounts import views


app_name = "accounts"
urlpatterns = [
    path("sign-up/", views.sign_up, name="sign-up"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("my-page/", views.my_page, name="my-page"),
]

base/urls.py
from django.urls import path

from base import views

urlpatterns = [
    path("", views.index)
]

blog/urls.py
from django.urls import path

from blog import views


app_name = "blog"
urlpatterns = [
    path("<int:blog_id>/", views.shop_blog_home, name="home"),
    path("<int:blog_id>/post/<int:post_id>/", views.shop_blog_post, name="post"),
    path("<int:blog_id>/post/write/", views.shop_blog_post_write, name="write"),
    path("<int:blog_id>/post/<int:post_id>/edit/", views.shop_blog_post_edit, name="edit"),
    path("<int:blog_id>/post/<int:post_id>/delete/", views.shop_blog_post_delete, name="delete")
]

django_demo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("landing.urls")),
    path("blog/", include("blog.urls")),
    path("shop/", include("shopping.urls")),
    path("payment/", include("payment.urls")),
    path("local/", include("local_shops.urls")),
    path("base/", include("base.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

landing/urls.py
from django.urls import path

from landing import views

app_name = "landing"
urlpatterns = [
    path("", views.index, name="home"),
]

local_shops/urls.py
from django.urls import path

from local_shops import views


app_name = "local"
urlpatterns = [
    path("local-shops/", views.local_shops, name="home"),
]

payment/urls.py
from django.urls import path

from payment import views


app_name = "payment"
urlpatterns = [
    path("cart/", views.payment_cart, name="cart"),
    path("purchase/", views.payment_purchase, name="purchase"),
    path("results/", views.payment_complete, name="results"),
]

shopping/urls.py
from django.urls import path

from shopping import views


app_name = "shop"
urlpatterns = [
    path("<int:shop_id>/", views.shop_home, name="home"),
    path("<int:shop_id>/item/<int:item_id>/", views.shop_item, name="item"),
    path("<int:shop_id>/admin/", views.shop_admin, name="admin"),
    path("<int:shop_id>/admin/item/add/", views.shop_admin_add_item, name="item-add"),
    path("<int:shop_id>/admin/item/<int:item_id>/edit/", views.shop_admin_edit, name="item-edit"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

from local_shops.models import Area
from shopping.models import Shop


class Info(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    area = models.ForeignKey(Area, on_delete=models.SET_NULL, null=True)
    is_shop_owner = models.BooleanField(default=False)


class Visited(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    shop = models.ForeignKey(Shop, on_delete=models.SET_NULL, null=True)

base/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models

from shopping.models import Shop


class Blog(models.Model):
    shop = models.OneToOneField(Shop, on_delete=models.SET_NULL, null=True)
    blog_name = models.CharField(max_length=32)
    blog_banner = models.ImageField(
        upload_to="blog/image/banner/",
        blank=True,
        null=True
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Post(models.Model):
    blog = models.ForeignKey(
        Blog,
        on_delete=models.SET_NULL,
        null=True,
        related_name="blog_posts"
    )
    title = models.CharField(max_length=32)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class PostImage(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.SET_NULL,
        related_name="post_images",
        null=True
    )
    image = models.ImageField(
        upload_to="blog/image/posts/%Y/%m/%d/",
        blank=True,
        null=True,
    )

local_shops/models.py
from django.db import models


class Area(models.Model):
    area_code = models.IntegerField()
    city_name = models.CharField(max_length=32)
    county_name = models.CharField(max_length=32)
    town_name = models.CharField(max_length=32)
    latitude = models.FloatField()
    longitude = models.FloatField()

payment/models.py
from django.db import models

from accounts.models import Info
from shopping.models import Item


class Purchases(models.Model):
    user = models.ForeignKey(
        Info,
        on_delete=models.SET_NULL,
        null=True
    )
    item = models.ForeignKey(
        Item,
        on_delete=models.SET_NULL,
        null=True
    )
    count = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=32, null=True)

shopping/models.py
from django.db import models

from local_shops.models import Area


class Shop(models.Model):
    user = models.OneToOneField(
        'accounts.Info',
        on_delete=models.SET_NULL,
        related_name="owning_shop",
        null=True
    )
    area = models.ForeignKey(
        Area,
        on_delete=models.SET_NULL,
        null=True,
        related_name="area_shops"
    )
    latitude = models.FloatField()
    longitude = models.FloatField()


class Item(models.Model):
    shop = models.ForeignKey(
        Shop,
        on_delete=models.SET_NULL,
        null=True
    )
    name = models.CharField(max_length=128)
    price = models.IntegerField()


class ItemImages(models.Model):
    item = models.ForeignKey(
        Item,
        on_delete=models.SET_NULL,
        related_name="item_images",
        null=True
    )
    image = models.ImageField(
        upload_to="shop/image/item/%Y/%m/%d/",
        blank=True,
        null=True,
    )

accounts/views.py
from django.shortcuts import render


def sign_up(request):
    return render(request, "accounts/sign-up.html")


def login(request):
    return render(request, "accounts/login.html")


def logout(request):
    return render(request, "accounts/log-out.html")


def my_page(request):
    return render(request, "accounts/my-page.html")

base/views.py
from django.shortcuts import render


def index(request):
    context = {

    }
    return render(request, "base.html", context=context)

blog/views.py
from django.shortcuts import render


def shop_blog_home(request, blog_id):
    return render(request, "blog/blog-home.html")


def shop_blog_post(request, blog_id, post_id):
    return render(request, "blog/blog-post.html")


def shop_blog_post_write(request, blog_id):
    return render(request, "blog/blog-post-write.html")


def shop_blog_post_edit(request, blog_id, post_id):
    return render(request, "blog/blog-post-edit.html")


def shop_blog_post_delete(request, blog_id, post_id):
    return render(request, "blog/blog-post-delete.html")

landing/views.py
from django.shortcuts import render


def index(request):
    return render(request, "landing/index.html")

local_shops/views.py
from django.shortcuts import render


def local_shops(request):
    return render(request, "local_shops/local-home.html")

payment/views.py
from django.shortcuts import render


def payment_cart(request):
    context = {

    }
    return render(request, "payment/payment-cart.html", context)


def payment_purchase(request):
    context = {

    }
    return render(request, "payment/payment-purchase.html", context)


def payment_complete(request):
    context = {

    }
    return render(request, "payment/payment-complete.html", context)

shopping/views.py
from django.shortcuts import render


def shop_home(request, shop_id):
    context = {

    }
    return render(request, "shopping/shop-home.html", context)


def shop_item(request, shop_id, item_id):
    context = {

    }
    return render(request, "shopping/shop-item.html", context)


def shop_admin(request, shop_id):
    context = {

    }
    return render(request, "shopping/shop-admin.html", context)


def shop_admin_add_item(request, shop_id):
    context = {

    }
    return render(request, "shopping/shop-admin-add.html", context)


def shop_admin_edit(request, shop_id, item_id):
    context = {

    }
    return render(request, "shopping/shop-admin-edit.html", context)

accounts/templates/accounts/log-out.html
{% extends 'base.html' %}

{% block title %}Log Out{% endblock %}

{% block content %}
<h1>Log Out</h1>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<h1>Login</h1>
{% endblock %}

accounts/templates/accounts/my-page.html
{% extends 'base.html' %}

{% block title %}My Page{% endblock %}

{% block content %}
<h1>My Page</h1>
{% endblock %}

accounts/templates/accounts/sign-up.html
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
<h1>Sign Up</h1>
{% endblock %}

blog/templates/blog/blog-home.html
{% extends "base.html" %}
{% block title %}Shop 1 Blog{% endblock %}
{% block content %}
<a href="{% url 'blog:post' 1 1 %}">Dummy Post Title</a>&nbsp;
Actions:&nbsp;
<a href="{% url 'blog:edit' 1 1 %}">Post Edit</a>&nbsp;
<a href="{% url 'blog:delete' 1 1 %}">Post Delete</a>
<div>
    <a href="{% url 'blog:write' 1 %}">Write Post</a>
</div>
<div>
    <a href="{% url 'shop:home' 1 %}">To Shop</a>&nbsp;
    <a href="{% url 'local:home' %}">Go Find More Shops</a>
</div>
{% endblock %}

blog/templates/blog/blog-post-delete.html
{% extends "base.html" %}
{% block title %}Shop 1 Blog Post 1 Delete{% endblock %}
{% block content %}
<h1>Blog 1 Post 1 Title</h1>
<p>Lorem ipsum</p>
<a href="{% url 'blog:home' 1 %}">Confirm</a>&nbsp;
<a href="{% url 'blog:home' 1 %}">Go Back</a>
{% endblock %}

blog/templates/blog/blog-post-edit.html
{% extends "base.html" %}
{% block title %}Shop 1 Blog Post 1 Edit{% endblock %}
{% block content %}
<h1>Title Input Label</h1>
<p>Content Input Label</p>
<a href="{% url 'blog:home' 1 %}">Confirm</a>&nbsp;
<a href="{% url 'blog:home' 1 %}">Go Back</a>
{% endblock %}

blog/templates/blog/blog-post-write.html
{% extends "base.html" %}
{% block title %}Shop 1 Blog Post Write{% endblock %}
{% block content %}
<h1>Title Input Label</h1>
<p>Content Input Label</p>
<a href="{% url 'blog:home' 1 %}">Confirm</a>&nbsp;
<a href="{% url 'blog:home' 1 %}">Go Back</a>
{% endblock %}

blog/templates/blog/blog-post.html
{% extends "base.html" %}
{% block title %}Shop 1 Blog Post 1{% endblock %}
{% block content %}
<h1>Blog 1 Post 1 Title</h1>
<p>Lorem ipsum</p>
<a href="{% url 'blog:home' 1 %}">Blog Home</a>&nbsp;
<a href="{% url 'blog:edit' 1 1 %}">Post Edit</a>&nbsp;
<a href="{% url 'blog:delete' 1 1 %}">Post Delete</a>
{% endblock %}

landing/templates/landing/index.html
{% extends 'base.html' %}

{% block title %}
Home - LIKELION
{% endblock %}

{% block content %}
<h1>Homepage</h1>
{% endblock %}

local_shops/templates/local_shops/local-home.html
{% extends 'base.html' %}
{% block content %}
<h1>Local Shops Info</h1>
<a href="{% url 'shop:home' 1 %}">Dummy Shop</a>&nbsp;
<a href="{% url 'blog:home' 1 %}">Dummy Shop Blog</a>
{% endblock %}

payment/templates/payment/payment-cart.html
{% extends 'base.html' %}

{% block title %}
My Cart
{% endblock %}

{% block content %}
<h1>Items Cart Page</h1>
    <a href="{% url 'payment:purchase' %}">Purchase Items in Cart</a>
{% endblock %}

payment/templates/payment/payment-complete.html
{% extends 'base.html' %}

{% block title %}
Purchase results
{% endblock %}

{% block content %}

<h1>Payment Completed Page</h1>
<a href="{% url 'landing:home' %}">Go back home</a>
{% endblock %}

payment/templates/payment/payment-purchase.html
{% extends 'base.html' %}

{% block title %}
Purchase Items in Cart
{% endblock %}

{% block content %}
<h1>Purchase Page</h1>
    <a href="{% url 'payment:results' %}">Confirm Purchase</a>
{% endblock %}

shopping/templates/shopping/shop-admin-add.html
{% extends 'base.html' %}

{% block title %}Shop Item Add{% endblock %}

{% block content %}
<h1>Shop Item Add</h1>
<a href="{% url 'shop:home' 1 %}">Go Back</a>
{% endblock %}

shopping/templates/shopping/shop-admin-edit.html
{% extends 'base.html' %}

{% block title %}Shop Item Edit{% endblock %}

{% block content %}
<h1>Shop Item Edit</h1>
<a href="{% url 'shop:home' 1 %}">Confirm</a>&nbsp;
<a href="{% url 'shop:home' 1 %}">Go Back</a>
{% endblock %}

shopping/templates/shopping/shop-admin.html
{% extends 'base.html' %}

{% block title %}shop 1 admin{% endblock %}

{% block content %}
<h1>Shop 1 Admin</h1>
<div>
    <a href="{% url 'shop:item-add' 1 %}">Item Add</a>
</div>
<div>
    <a href="{% url 'shop:item-edit' 1 1 %}">Dummy Item Edit</a>
</div>
<div>
    <a href="{% url 'shop:home' 1 %}">Go Back</a>
</div>
{% endblock %}

shopping/templates/shopping/shop-home.html
{% extends 'base.html' %}

{% block title %}shop 1 home{% endblock %}

{% block content %}
<h1>Shop 1</h1>
<div>
    <a href="{% url 'shop:item' 1 1 %}">Dummy Item</a>
</div>
<div>
    <a href="{% url 'blog:home' 1 %}">To Blog</a>&nbsp;
    <a href="{% url 'shop:admin' 1 %}">To Admin</a>
</div>
<div>
    <a href="{% url 'local:home' %}">Go Back</a>
</div>
{% endblock %}

shopping/templates/shopping/shop-item.html
{% extends 'base.html' %}

{% block title %}shop item{% endblock %}

{% block content %}
<h1>Shop Item 1-1</h1>
<a href="{% url 'shop:home' 1 %}">Go Back</a>
{% endblock %}